#!/usr/bin/env bash
# installs nginx and configure it to listen on port 80
# print "Hello World"

sudo apt-get update
sudo apt-get -y install nginx
#echo 'Hello World!' > /var/www/html/index.html
#service nginx start
#echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
#apt-get update
#apt-get install -y nginx

mkdir /var/nginx/html
touch /var/nginx/html/index.html
echo "Hello World!" > /var/nginx/html/index.html
printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /etc/nginx/html;
     index       index.html index.htm;
}
" > /var/nginx/sites-available/default

service nginx restart