#!/usr/bin/env bash
#configure a custom 404 page

apt-get -y update
apt-get -y install nginx
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
error_line='\n\t error_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}'
sed -i "/server_name _;/a \ $error_line" /etc/nginx/sites-enabled/default
sudo /etc/init.d/nginx restart
