#!/usr/bin/env bash
# Displays "Best School" 10 times using a while loop.
#   On the 9th iteration, displays "Hi" before "Best School".

x=1
while [ $x -ne 11 ]
do
  if [ $x -eq 9 ]
  then
    echo "Hi"
  else
    echo "Best School"
  fi
  x=$(( x + 1 ))
done